POST http://localhost:8087/api/v1/swdocs
Content-Type: application/json

{
  "name": "zerom2q",
  "description": "A library that abstracts sockets",
    "sections": [
      {"header": "Dashboards", "links": [{"url": "http://kibana.domain.com:5601", "description": "Kibana boards"}]}
    ]
}

###